source "http://rubygems.org"
gem 'ckeditor', git: 'git://github.com/lafeber/ckeditor.git'
gem 'frontendeditor_ckeditor', github: 'GCorbel/frontendeditor_ckeditor'
gem 'frontendeditor', github: 'GCorbel/frontendeditor'
